//! The damaged reference vault `broken_health` and its manifest of expected findings.
//!
//! `tests/fixtures/broken_health` is generated by `tools/fixture-gen` (`-Dfixture.cmd=broken`) and
//! carries nine deliberate damages on the ciphertext level. `expected-findings.json` lists exactly
//! the nine non-GOOD findings the real cryptofs 2.10.0 health checks report for it and is the
//! authority for every health check test — never a hard-coded count somewhere else.
mod common;

use serde::Deserialize;

/// One entry of `expected-findings.json`.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ExpectedFinding {
    /// `dirid`, `type` or `shortened` — the check that reports the finding.
    pub check: String,
    /// `INFO`, `WARN` or `CRITICAL`. GOOD results are not listed.
    pub severity: String,
    /// The name of the Java `DiagnosticResult` class, e.g. `OrphanContentDir`.
    pub result: String,
    /// Vault-relative path of the damaged node, `/` separated.
    pub path: String,
}

pub fn expected_findings() -> Vec<ExpectedFinding> {
    let raw = std::fs::read_to_string(
        common::fixtures_root()
            .join("broken_health")
            .join("expected-findings.json"),
    )
    .expect("expected-findings.json (run tools/fixture-gen -Dfixture.cmd=broken)");
    serde_json::from_str(&raw).expect("valid manifest")
}

#[test]
fn the_broken_fixture_carries_nine_expected_findings() {
    let findings = expected_findings();
    assert_eq!(findings.len(), 9, "{findings:#?}");

    let results: Vec<&str> = findings.iter().map(|f| f.result.as_str()).collect();
    for expected in [
        "OrphanContentDir",
        "MissingDirIdBackup",
        "MissingContentDir",
        "LooseDirFile",
        "DirIdCollision",
        "UnknownType",
        "LongShortNamesMismatch",
        "TrailingBytesInNameFile",
        "MissingLongName",
    ] {
        assert!(
            results.contains(&expected),
            "{expected} missing: {results:?}"
        );
    }

    for finding in &findings {
        assert!(
            matches!(finding.check.as_str(), "dirid" | "type" | "shortened"),
            "unknown check: {finding:?}"
        );
        assert!(
            matches!(finding.severity.as_str(), "INFO" | "WARN" | "CRITICAL"),
            "GOOD results do not belong into the manifest: {finding:?}"
        );
        assert!(
            !finding.path.starts_with('/') && finding.path.starts_with("d/"),
            "paths are vault-relative and point into the data dir: {finding:?}"
        );
    }
}

#[test]
fn every_recorded_finding_points_at_something_that_exists() {
    let (_tmp, vault) = common::fixture_copy_at("broken_health");
    for finding in expected_findings() {
        let path = finding
            .path
            .split('/')
            .fold(vault.clone(), |acc, part| acc.join(part));
        assert!(
            path.exists(),
            "{} does not exist: {finding:?}",
            path.display()
        );
    }
}

#[test]
fn the_broken_fixture_still_unlocks() {
    // Only the structure is damaged; masterkey and vault config stay valid, so a health check can
    // derive the cryptor it needs. `open_vault` writes backup files, hence the copy.
    let (_tmp, vault) = common::fixture_copy_at("broken_health");
    cryptomator_core::open_vault(
        &vault,
        &cryptomator_core::MasterkeyFileAccess::new(Vec::new()),
        common::PASSPHRASE,
    )
    .expect("the damaged vault still opens");
}

#[test]
fn a_check_context_is_built_from_the_unlocked_broken_fixture() {
    let (_tmp, vault) = common::fixture_copy_at("broken_health");
    let meta = common::fixture_meta(&vault);
    let opened = cryptomator_core::open_vault(
        &vault,
        &cryptomator_core::MasterkeyFileAccess::new(Vec::new()),
        &meta.passphrase,
    )
    .expect("the damaged vault still opens");

    let ctx = cryptomator_core::CheckContext::from_opened(opened);
    assert_eq!(ctx.vault_path, vault);
    assert_eq!(ctx.data_dir(), vault.join("d"));
    assert!(ctx.data_dir().is_dir());
    assert_eq!(ctx.shortening_threshold, meta.shortening_threshold as usize);
    assert_eq!(ctx.config.vault_version, cryptomator_core::VAULT_VERSION);
    assert_eq!(ctx.config.cipher_combo.as_str(), meta.cipher_combo);

    // The context carries a working cryptor: the root content dir it addresses must exist.
    let root = cryptomator_core::root_content_dir(&ctx.vault_path, &ctx.cryptor);
    assert!(root.is_dir(), "{} is missing", root.display());

    // Every check of the catalogue runs against this context; the findings are asserted one by one
    // further down.
    let findings = cryptomator_core::run_checks(&cryptomator_core::CHECK_IDS, &ctx, &mut |_| {})
        .expect("the catalogue ids are known");
    assert!(!findings.is_empty(), "{findings:#?}");
}

// ---------------------------------------------------------------------------------------------
// Task 4: the `dirid` check against the damaged fixture.
// ---------------------------------------------------------------------------------------------

use cryptomator_core::{
    CheckContext, CleartextPath, CryptoFs, CryptoFsOptions, DiagnosticResult, Masterkey,
    OpenedVault, Severity,
};
use data_encoding::HEXLOWER;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Unlocks a fixture copy with its raw masterkey — no scrypt, so a test may unlock repeatedly.
fn unlock(vault: &Path) -> OpenedVault {
    let meta = common::fixture_meta(vault);
    let raw = HEXLOWER
        .decode(meta.masterkey_hex.as_bytes())
        .expect("the manifest carries a hex masterkey");
    let mut key = [0u8; 64];
    key.copy_from_slice(&raw);
    cryptomator_core::open_vault_with_key(vault, Masterkey::from_raw(key))
        .expect("the fixture unlocks")
}

fn context(name: &str) -> (tempfile::TempDir, PathBuf, CheckContext) {
    let (tmp, vault) = common::fixture_copy_at(name);
    let ctx = CheckContext::from_opened(unlock(&vault));
    (tmp, vault, ctx)
}

fn dirid(ctx: &CheckContext) -> Vec<DiagnosticResult> {
    cryptomator_core::run_checks(&["dirid"], ctx, &mut |_| {}).expect("`dirid` is a known check")
}

/// How often each result kind occurs. The manifest names the findings by kind, and only by kind:
/// two of the nine paths are named after random directory ids and the `DirIdCollision` path depends
/// on the directory order, so counting kinds is the only stable comparison (Task 1 report).
fn by_kind(results: &[DiagnosticResult]) -> BTreeMap<&'static str, usize> {
    let mut counts = BTreeMap::new();
    for result in results {
        *counts.entry(result.kind).or_insert(0) += 1;
    }
    counts
}

fn count_kind(results: &[DiagnosticResult], kind: &str) -> usize {
    results.iter().filter(|r| r.kind == kind).count()
}

fn slashed(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

/// The manifest's entries for one check, folded to `kind -> (count, severity)`. The manifest is the
/// authority for every count in here — never a literal `1` in a test.
fn expected_for(check: &str) -> BTreeMap<String, (usize, String)> {
    let mut expected: BTreeMap<String, (usize, String)> = BTreeMap::new();
    for finding in expected_findings().into_iter().filter(|f| f.check == check) {
        let entry = expected
            .entry(finding.result.clone())
            .or_insert((0, finding.severity.clone()));
        entry.0 += 1;
        assert_eq!(
            entry.1, finding.severity,
            "the manifest gives {} two severities",
            finding.result
        );
    }
    expected
}

/// Applies every fix the report offers, in report order.
fn apply_fixes(ctx: &CheckContext, results: &[DiagnosticResult]) {
    for result in results {
        if let Some(fix) = &result.fix {
            fix.apply(ctx)
                .unwrap_or_else(|e| panic!("{} fix failed: {e}", result.kind));
        }
    }
}

/// The cleartext name of the step parent the adoption creates for `content_dir`: the two path
/// components of `d/XX/YYYY…`, concatenated (`OrphanContentDir.fix`).
fn step_parent_name(content_dir: &Path) -> String {
    let component = |p: Option<&Path>| {
        p.and_then(Path::file_name)
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned()
    };
    format!(
        "{}{}",
        component(content_dir.parent()),
        component(Some(content_dir))
    )
}

fn names_of(entries: &[cryptomator_core::DirEntry]) -> Vec<&str> {
    entries.iter().map(|e| e.cleartext_name.as_str()).collect()
}

#[test]
fn the_dirid_check_finds_exactly_the_manifest_findings() {
    let (_tmp, _vault, ctx) = context("broken_health");
    let results = dirid(&ctx);
    assert!(results.iter().all(|r| r.check == "dirid"), "{results:#?}");

    let expected = expected_for("dirid");
    assert_eq!(expected.len(), 5, "{expected:#?}");
    let found = by_kind(&results);
    for (kind, (count, severity)) in &expected {
        assert_eq!(
            found.get(kind.as_str()).copied().unwrap_or(0),
            *count,
            "{kind}: {results:#?}"
        );
        for result in results.iter().filter(|r| r.kind == kind.as_str()) {
            assert_eq!(result.severity.as_str(), severity, "{kind}");
        }
    }

    // The intact directories are still good, and nothing beyond the manifest is reported.
    assert!(
        found.get("HealthyDir").copied().unwrap_or(0) >= 1,
        "{results:#?}"
    );
    for result in &results {
        assert!(
            expected.contains_key(result.kind) || result.severity == Severity::Good,
            "unexpected finding: {result:#?}"
        );
    }

    // Every reported path is vault-relative and points into the data dir.
    assert!(
        results
            .iter()
            .flat_map(|r| &r.paths)
            .all(|p| p.is_relative() && p.starts_with("d")),
        "{results:#?}"
    );
}

#[test]
fn the_stable_manifest_paths_are_reported_verbatim() {
    // Only these two `dirid` paths are stable: `OrphanContentDir` and `MissingDirIdBackup` are named
    // after random directory ids, and which of the two colliding `dir.c9r` files `DirIdCollision`
    // names depends on the directory order (Task 1 report).
    let (_tmp, _vault, ctx) = context("broken_health");
    let results = dirid(&ctx);
    for kind in ["LooseDirFile", "MissingContentDir"] {
        let expected = expected_findings()
            .into_iter()
            .find(|f| f.result == kind)
            .unwrap_or_else(|| panic!("no {kind} in the manifest"))
            .path;
        assert!(
            results
                .iter()
                .filter(|r| r.kind == kind)
                .any(|r| r.paths.iter().any(|p| slashed(p) == expected)),
            "{kind} does not name {expected}: {results:#?}"
        );
    }
}

#[test]
fn an_intact_vault_yields_only_good_dirid_results() {
    let (_tmp, _vault, ctx) = context("nested");
    let results = dirid(&ctx);
    assert!(!results.is_empty());
    assert!(
        results.iter().all(|r| r.severity == Severity::Good),
        "{results:#?}"
    );
    assert!(results.iter().all(|r| !r.fixable()), "{results:#?}");
}

#[test]
fn the_dirid_fixes_repair_the_vault_and_are_idempotent() {
    let (_tmp, vault, ctx) = context("broken_health");
    let before = dirid(&ctx);
    assert!(
        before
            .iter()
            .any(|r| r.kind == "OrphanContentDir" && r.fixable()),
        "{before:#?}"
    );
    // Before the repair the directory whose content dir is missing is not even listable.
    let fs = CryptoFs::open(unlock(&vault), CryptoFsOptions::default());
    assert!(
        !names_of(&fs.read_dir(&CleartextPath::root()).expect("the root lists"))
            .contains(&"nocontent"),
        "the broken directory is filtered out while its content dir is missing"
    );
    drop(fs);

    apply_fixes(&ctx, &before);
    let after = dirid(&ctx);
    for kind in [
        "LooseDirFile",
        "MissingDirIdBackup",
        "MissingContentDir",
        "OrphanContentDir",
    ] {
        // `MissingDirIdBackup` reappears below for the freshly created recovery directory, but the
        // one the fixture carries is repaired.
        if kind != "MissingDirIdBackup" {
            assert_eq!(count_kind(&after, kind), 0, "{kind}: {after:#?}");
        }
    }
    // Java's `prepareRecoveryDir` writes no `dirid.c9r` for /LOST+FOUND, so the adoption leaves
    // exactly one new INFO finding for the next pass to repair.
    assert_eq!(count_kind(&after, "MissingDirIdBackup"), 1, "{after:#?}");
    // The collision is unfixable in Java too.
    assert_eq!(count_kind(&after, "DirIdCollision"), 1, "{after:#?}");

    apply_fixes(&ctx, &after);
    let settled = dirid(&ctx);
    assert_eq!(
        count_kind(&settled, "MissingDirIdBackup"),
        0,
        "{settled:#?}"
    );
    // A further round changes nothing at all.
    apply_fixes(&ctx, &settled);
    assert_eq!(by_kind(&dirid(&ctx)), by_kind(&settled));

    // The repaired vault still opens, the repaired directory now lists (empty, its content was
    // never there — the fix restores the structure, not the data) and the adopted files of the
    // orphan are reachable below /LOST+FOUND.
    let fs = CryptoFs::open(unlock(&vault), CryptoFsOptions::default());
    let root = fs.read_dir(&CleartextPath::root()).expect("the root lists");
    assert!(names_of(&root).contains(&"nocontent"), "{root:#?}");
    assert!(names_of(&root).contains(&"LOST+FOUND"), "{root:#?}");
    assert!(fs
        .read_dir(&CleartextPath::parse("/nocontent"))
        .expect("the repaired directory lists")
        .is_empty());

    let lost_and_found = CleartextPath::parse("/LOST+FOUND");
    let step_parents = fs
        .read_dir(&lost_and_found)
        .expect("/LOST+FOUND lists after the adoption");
    let orphan_path = before
        .iter()
        .find(|r| r.kind == "OrphanContentDir")
        .map(|r| r.paths[0].clone())
        .expect("the orphan was reported");
    assert_eq!(
        names_of(&step_parents),
        vec![step_parent_name(&orphan_path).as_str()],
        "one step parent per adopted orphan"
    );
    let step_parent = lost_and_found
        .join(&step_parents[0].cleartext_name)
        .expect("a hash is a valid file name");
    let adopted = fs.read_dir(&step_parent).expect("the step parent lists");
    // The orphan still had its `dirid.c9r`, so the original names could be decrypted.
    assert_eq!(
        names_of(&adopted),
        vec!["adopted.txt", "second.txt"],
        "{adopted:#?}"
    );

    // …and the payload of an adopted file is readable through the cleartext layer.
    let file = step_parent.join("adopted.txt").expect("a valid file name");
    let handle = fs
        .open_file(&file, cryptomator_core::OpenOptions::read_only())
        .expect("the adopted file opens");
    let size = handle.size();
    assert!(size > 0, "the adopted file is not empty");
    let mut buf = vec![0u8; size as usize];
    assert_eq!(
        handle.read_at(&mut buf, 0).expect("the file reads"),
        buf.len()
    );
}

/// The specifics of `OrphanContentDir.fix`: the `/LOST+FOUND` node in the vault root carries the
/// dir id `recovery`, the step parent is named after the orphan's hash, and a shortened node stays
/// shortened. The fixture's orphan holds no `.c9s`, so this test adds one to the copy.
#[test]
fn the_orphan_adoption_builds_lost_and_found_the_way_java_does() {
    let (_tmp, vault, ctx) = context("broken_health");
    let orphan_rel = dirid(&ctx)
        .into_iter()
        .find(|r| r.kind == "OrphanContentDir")
        .expect("the fixture carries an orphan")
        .paths[0]
        .clone();
    let orphan = ctx.resolve(&orphan_rel);

    // A shortened node whose `name.c9s` does not decrypt: the adoption has to fall back to
    // `file<n>_<runId>_withVeryLongName…` and shorten that name again.
    let c9s = orphan.join(format!("{}.c9s", "D".repeat(32)));
    std::fs::create_dir_all(&c9s).unwrap();
    std::fs::write(c9s.join("contents.c9r"), b"unreadable").unwrap();
    std::fs::write(c9s.join("name.c9s"), b"notACiphertextName.c9r").unwrap();

    let orphan_result = dirid(&ctx)
        .into_iter()
        .find(|r| r.kind == "OrphanContentDir")
        .expect("still an orphan");
    let fix = orphan_result.fix.as_ref().expect("the orphan is fixable");
    assert!(fix.describe().contains("LOST+FOUND"), "{}", fix.describe());
    fix.apply(&ctx).expect("the adoption succeeds");
    assert!(!orphan.exists(), "the orphaned content dir was removed");

    // `/LOST+FOUND` sits in the vault root and its `dir.c9r` names the fixed recovery id.
    let root = cryptomator_core::root_content_dir(&vault, &ctx.cryptor);
    let cipher_name = format!(
        "{}.c9r",
        ctx.cryptor
            .file_name_cryptor()
            .encrypt_filename("LOST+FOUND", &[b""])
    );
    let dir_file = root.join(&cipher_name).join("dir.c9r");
    assert_eq!(std::fs::read_to_string(&dir_file).unwrap(), "recovery");

    // The step parent below it is named after the orphan and holds the three adopted nodes.
    let fs = CryptoFs::open(unlock(&vault), CryptoFsOptions::default());
    let step_parent = CleartextPath::parse("/LOST+FOUND")
        .join(&step_parent_name(&orphan_rel))
        .expect("a hash is a valid file name");
    let adopted = fs.read_dir(&step_parent).expect("the step parent lists");
    let names = names_of(&adopted);
    assert!(names.contains(&"adopted.txt"), "{adopted:#?}");
    assert!(names.contains(&"second.txt"), "{adopted:#?}");
    let generated = names
        .iter()
        .find(|n| n.starts_with("file"))
        .unwrap_or_else(|| panic!("the undecryptable node was renamed: {adopted:#?}"));
    assert!(generated.contains("_withVeryLongName"), "{generated}");

    // Its ciphertext is a `.c9s` directory again, with a `name.c9s` holding the full name. The
    // step parent's content dir is found the way the mapper would: recovery id -> hash -> the step
    // parent's own `dir.c9r` -> hash.
    let step_cipher = format!(
        "{}.c9r",
        ctx.cryptor
            .file_name_cryptor()
            .encrypt_filename(&step_parent_name(&orphan_rel), &[b"recovery"])
    );
    let recovery_hash = ctx
        .cryptor
        .file_name_cryptor()
        .hash_directory_id("recovery");
    let step_dir_id = std::fs::read_to_string(
        ctx.data_dir()
            .join(&recovery_hash[..2])
            .join(&recovery_hash[2..])
            .join(&step_cipher)
            .join("dir.c9r"),
    )
    .expect("the step parent has a dir.c9r");
    let step_hash = ctx
        .cryptor
        .file_name_cryptor()
        .hash_directory_id(&step_dir_id);
    let step_content_dir = ctx.data_dir().join(&step_hash[..2]).join(&step_hash[2..]);
    let shortened: Vec<PathBuf> = std::fs::read_dir(&step_content_dir)
        .unwrap()
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().is_some_and(|e| e == "c9s"))
        .collect();
    assert_eq!(shortened.len(), 1, "{shortened:#?}");
    let long_name = std::fs::read_to_string(shortened[0].join("name.c9s"))
        .expect("the adopted .c9s carries a name.c9s");
    assert!(long_name.ends_with(".c9r"), "{long_name}");
    assert!(
        long_name.len() > ctx.shortening_threshold,
        "the generated name really needed shortening: {}",
        long_name.len()
    );
    assert!(shortened[0].join("contents.c9r").is_file(), "content moved");
}

// ---------------------------------------------------------------------------------------------
// Task 6: the `type` and `shortened` checks against the damaged fixture.
// ---------------------------------------------------------------------------------------------

use cryptomator_core::health::shortened::deflate_name;

fn run(ctx: &CheckContext, id: &str) -> Vec<DiagnosticResult> {
    cryptomator_core::run_checks(&[id], ctx, &mut |_| {}).expect("a known check")
}

/// Asserts that `results` carries exactly the manifest's findings for `check` — every listed kind
/// with its count and its severity, and nothing beyond them that is not `GOOD`.
fn assert_matches_manifest(check: &str, results: &[DiagnosticResult]) {
    assert!(results.iter().all(|r| r.check == check), "{results:#?}");
    let expected = expected_for(check);
    assert!(
        !expected.is_empty(),
        "the manifest lists nothing for {check}"
    );
    let found = by_kind(results);
    for (kind, (count, severity)) in &expected {
        assert_eq!(
            found.get(kind.as_str()).copied().unwrap_or(0),
            *count,
            "{kind}: {results:#?}"
        );
        for result in results.iter().filter(|r| r.kind == kind.as_str()) {
            assert_eq!(result.severity.as_str(), severity, "{kind}");
        }
    }
    for result in results {
        assert!(
            expected.contains_key(result.kind) || result.severity == Severity::Good,
            "unexpected finding: {result:#?}"
        );
    }
    assert!(
        results
            .iter()
            .flat_map(|r| &r.paths)
            .all(|p| p.is_relative() && p.starts_with("d")),
        "{results:#?}"
    );
}

/// Applies every fix and reports which ones refused. `UnknownType` on a non-empty node is expected
/// to refuse, so the fix-all test cannot simply `expect` its way through the report.
fn apply_fixes_reporting_failures(
    ctx: &CheckContext,
    results: &[DiagnosticResult],
) -> Vec<(&'static str, String)> {
    let mut failures = Vec::new();
    for result in results {
        if let Some(fix) = &result.fix {
            if let Err(e) = fix.apply(ctx) {
                failures.push((result.kind, e.to_string()));
            }
        }
    }
    failures
}

#[test]
fn the_type_check_finds_exactly_the_manifest_findings() {
    let (_tmp, _vault, ctx) = context("broken_health");
    let results = run(&ctx, "type");
    assert_matches_manifest("type", &results);

    // The intact nodes of the fixture are all of a determined type.
    let known = count_kind(&results, "KnownType");
    assert!(known >= 5, "{results:#?}");
    assert_eq!(known + count_kind(&results, "UnknownType"), results.len());
    for result in results.iter().filter(|r| r.kind == "KnownType") {
        assert!(
            ["DIRECTORY.", "SYMLINK.", "FILE."]
                .iter()
                .any(|suffix| result.message.ends_with(suffix)),
            "{}",
            result.message
        );
        assert!(!result.fixable(), "a good node has nothing to repair");
    }
    // The one damaged node is named verbatim, and only it is fixable.
    let unknown = results
        .iter()
        .find(|r| r.kind == "UnknownType")
        .expect("the manifest lists an UnknownType");
    assert_eq!(
        slashed(&unknown.paths[0]),
        expected_findings()
            .into_iter()
            .find(|f| f.result == "UnknownType")
            .expect("in the manifest")
            .path
    );
    assert!(unknown.fixable());
}

#[test]
fn the_shortened_check_finds_exactly_the_manifest_findings() {
    let (_tmp, _vault, ctx) = context("broken_health");
    let results = run(&ctx, "shortened");
    assert_matches_manifest("shortened", &results);

    // The fixture carries one intact `.c9s` node for contrast.
    assert_eq!(
        count_kind(&results, "ValidShortenedFile"),
        1,
        "{results:#?}"
    );
    // Only the two WARN findings can be repaired; `MissingLongName` has no fix in Java either.
    for result in &results {
        assert_eq!(
            result.fixable(),
            matches!(
                result.kind,
                "TrailingBytesInNameFile" | "LongShortNamesMismatch"
            ),
            "{result:#?}"
        );
    }
    // Each of the three damaged nodes is named verbatim.
    for finding in expected_findings()
        .into_iter()
        .filter(|f| f.check == "shortened")
    {
        assert!(
            results
                .iter()
                .filter(|r| r.kind == finding.result)
                .any(|r| r.paths.iter().any(|p| slashed(p) == finding.path)),
            "{} does not name {}: {results:#?}",
            finding.result,
            finding.path
        );
    }
}

#[test]
fn the_type_and_shortened_fixes_repair_what_they_can() {
    let (_tmp, vault, ctx) = context("broken_health");
    let root = cryptomator_core::root_content_dir(&vault, &ctx.cryptor);

    // The name the mismatched `.c9s` directory should have, straight from its own `name.c9s`.
    let mismatch = run(&ctx, "shortened")
        .into_iter()
        .find(|r| r.kind == "LongShortNamesMismatch")
        .expect("the fixture carries a mismatch");
    let mismatch_dir = ctx.resolve(&mismatch.paths[0]);
    let long_name = std::fs::read_to_string(mismatch_dir.join("name.c9s")).expect("a name file");
    let expected_short_name = deflate_name(&long_name);
    assert!(
        !root.join(&expected_short_name).exists(),
        "the expected name is free, so the fix is a real rename"
    );

    let before: Vec<DiagnosticResult> = ["type", "shortened"]
        .iter()
        .flat_map(|id| run(&ctx, id))
        .collect();
    let failures = apply_fixes_reporting_failures(&ctx, &before);
    // `UnknownType.fix` is Java's `Files.delete`, which refuses a non-empty directory — and the
    // fixture's unknown node holds a file (an empty directory does not survive git).
    assert_eq!(failures.len(), 1, "{failures:#?}");
    assert_eq!(failures[0].0, "UnknownType");

    let after: Vec<DiagnosticResult> = ["type", "shortened"]
        .iter()
        .flat_map(|id| run(&ctx, id))
        .collect();
    assert_eq!(
        count_kind(&after, "TrailingBytesInNameFile"),
        0,
        "the trailing bytes were cut: {after:#?}"
    );
    assert_eq!(
        count_kind(&after, "LongShortNamesMismatch"),
        0,
        "the c9s dir was renamed: {after:#?}"
    );
    // Both repaired nodes are valid shortened resources now — one more than before.
    assert_eq!(count_kind(&after, "ValidShortenedFile"), 3, "{after:#?}");
    assert_eq!(
        count_kind(&after, "MissingLongName"),
        1,
        "MissingLongName has no fix: {after:#?}"
    );
    assert_eq!(
        count_kind(&after, "UnknownType"),
        1,
        "a non-empty node of unknown type is never deleted: {after:#?}"
    );

    // The rename really happened, and it is the name the long name deflates to.
    assert!(!mismatch_dir.exists(), "the old name is gone");
    let renamed = root.join(&expected_short_name);
    assert!(
        renamed.join("contents.c9r").is_file(),
        "content moved along"
    );
    assert_eq!(
        std::fs::read_to_string(renamed.join("name.c9s")).unwrap(),
        long_name
    );

    // A second round changes nothing: the fixes are idempotent and the report has settled.
    let failures = apply_fixes_reporting_failures(&ctx, &after);
    assert_eq!(failures.len(), 1, "{failures:#?}");
    let settled: Vec<DiagnosticResult> = ["type", "shortened"]
        .iter()
        .flat_map(|id| run(&ctx, id))
        .collect();
    assert_eq!(by_kind(&settled), by_kind(&after));

    // The repaired vault opens and lists both repaired files under their real cleartext names.
    let fs = CryptoFs::open(unlock(&vault), CryptoFsOptions::default());
    let entries = fs.read_dir(&CleartextPath::root()).expect("the root lists");
    let names = names_of(&entries);
    // Damage 7 pointed the `name.c9s` at a synthetic name, so the renamed node lists as that name.
    let renamed_cleartext = format!("{}.txt", "S".repeat(200));
    assert!(names.contains(&renamed_cleartext.as_str()), "{names:#?}");
    // Damage 8's node only becomes listable once the trailing bytes are gone.
    let truncated_cleartext = format!("{}.txt", "T".repeat(200));
    assert!(names.contains(&truncated_cleartext.as_str()), "{names:#?}");
}

#[test]
fn an_empty_unknown_node_is_deleted_by_the_type_fix() {
    let (_tmp, vault, ctx) = context("broken_health");
    // The same damage the fixture carries, only empty — the way the desktop app leaves it behind.
    // Git cannot track an empty directory, so the fixture's node holds a file instead.
    let root = cryptomator_core::root_content_dir(&vault, &ctx.cryptor);
    let name = format!(
        "{}.c9r",
        ctx.cryptor
            .file_name_cryptor()
            .encrypt_filename("empty", &[b""])
    );
    std::fs::create_dir(root.join(&name)).unwrap();

    let found = run(&ctx, "type")
        .into_iter()
        .find(|r| r.paths.iter().any(|p| p.ends_with(&name)))
        .expect("the empty node is reported");
    assert_eq!(found.kind, "UnknownType");
    let fix = found.fix.as_ref().expect("an unknown node is deletable");
    fix.apply(&ctx).expect("the empty node is deleted");
    assert!(!root.join(&name).exists());
    // Applying it again is a no-op, not a `NotFound`.
    fix.apply(&ctx).expect("idempotent");
}

#[test]
fn a_healthy_vault_passes_all_three_checks() {
    let mut seen_per_check: BTreeMap<&str, usize> = BTreeMap::new();
    for name in common::FIXTURE_NAMES {
        let (_tmp, _vault, ctx) = context(name);
        let results = cryptomator_core::run_checks(&cryptomator_core::CHECK_IDS, &ctx, &mut |_| {})
            .expect("the catalogue ids are known");
        assert!(!results.is_empty(), "{name}");
        let bad: Vec<_> = results
            .iter()
            .filter(|r| r.severity > Severity::Good)
            .collect();
        assert!(bad.is_empty(), "{name}: {bad:#?}");
        assert!(results.iter().all(|r| !r.fixable()), "{name}: {results:#?}");
        // `dirid` always has something to say, so "no findings" is never the reason for the green
        // result. `type` needs a node *directory* (`sizes` holds nothing but plain files) and
        // `shortened` a `.c9s` node, so those two are counted over the whole set instead.
        assert!(results.iter().any(|r| r.check == "dirid"), "{name}");
        for result in &results {
            *seen_per_check.entry(result.check).or_insert(0) += 1;
        }
    }
    for id in cryptomator_core::CHECK_IDS {
        assert!(
            seen_per_check.get(id).copied().unwrap_or(0) > 0,
            "no fixture exercised {id}: {seen_per_check:#?}"
        );
    }
}
