//! The damaged reference vault `broken_health` and its manifest of expected findings.
//!
//! `tests/fixtures/broken_health` is generated by `tools/fixture-gen` (`-Dfixture.cmd=broken`) and
//! carries nine deliberate damages on the ciphertext level. `expected-findings.json` lists exactly
//! the nine non-GOOD findings the real cryptofs 2.10.0 health checks report for it and is the
//! authority for every health check test — never a hard-coded count somewhere else.
mod common;

use serde::Deserialize;

/// One entry of `expected-findings.json`.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ExpectedFinding {
    /// `dirid`, `type` or `shortened` — the check that reports the finding.
    pub check: String,
    /// `INFO`, `WARN` or `CRITICAL`. GOOD results are not listed.
    pub severity: String,
    /// The name of the Java `DiagnosticResult` class, e.g. `OrphanContentDir`.
    pub result: String,
    /// Vault-relative path of the damaged node, `/` separated.
    pub path: String,
}

pub fn expected_findings() -> Vec<ExpectedFinding> {
    let raw = std::fs::read_to_string(
        common::fixtures_root()
            .join("broken_health")
            .join("expected-findings.json"),
    )
    .expect("expected-findings.json (run tools/fixture-gen -Dfixture.cmd=broken)");
    serde_json::from_str(&raw).expect("valid manifest")
}

#[test]
fn the_broken_fixture_carries_nine_expected_findings() {
    let findings = expected_findings();
    assert_eq!(findings.len(), 9, "{findings:#?}");

    let results: Vec<&str> = findings.iter().map(|f| f.result.as_str()).collect();
    for expected in [
        "OrphanContentDir",
        "MissingDirIdBackup",
        "MissingContentDir",
        "LooseDirFile",
        "DirIdCollision",
        "UnknownType",
        "LongShortNamesMismatch",
        "TrailingBytesInNameFile",
        "MissingLongName",
    ] {
        assert!(
            results.contains(&expected),
            "{expected} missing: {results:?}"
        );
    }

    for finding in &findings {
        assert!(
            matches!(finding.check.as_str(), "dirid" | "type" | "shortened"),
            "unknown check: {finding:?}"
        );
        assert!(
            matches!(finding.severity.as_str(), "INFO" | "WARN" | "CRITICAL"),
            "GOOD results do not belong into the manifest: {finding:?}"
        );
        assert!(
            !finding.path.starts_with('/') && finding.path.starts_with("d/"),
            "paths are vault-relative and point into the data dir: {finding:?}"
        );
    }
}

#[test]
fn every_recorded_finding_points_at_something_that_exists() {
    let (_tmp, vault) = common::fixture_copy_at("broken_health");
    for finding in expected_findings() {
        let path = finding
            .path
            .split('/')
            .fold(vault.clone(), |acc, part| acc.join(part));
        assert!(
            path.exists(),
            "{} does not exist: {finding:?}",
            path.display()
        );
    }
}

#[test]
fn the_broken_fixture_still_unlocks() {
    // Only the structure is damaged; masterkey and vault config stay valid, so a health check can
    // derive the cryptor it needs. `open_vault` writes backup files, hence the copy.
    let (_tmp, vault) = common::fixture_copy_at("broken_health");
    cryptomator_core::open_vault(
        &vault,
        &cryptomator_core::MasterkeyFileAccess::new(Vec::new()),
        common::PASSPHRASE,
    )
    .expect("the damaged vault still opens");
}
