//! `cargo xtask formula`: the Homebrew formula for a release's tarballs.
//!
//! Rendered rather than hand-edited, because the urls and the checksums change with every release
//! and a formula with a stale sha256 fails at install time with a message nobody can act on.
//!
//! Four archives, not one: Homebrew runs on Linux too, and a formula that offered a macOS binary
//! there would install something that cannot start. The macOS Universal tarball `xtask lipo`
//! builds is *not* what the formula points at -- Homebrew already knows the machine's
//! architecture, so the per-architecture archive is half the download.
use crate::dist::archive_name;

/// The macOS arm64 archive's target triple.
pub(crate) const MACOS_ARM64: &str = "aarch64-apple-darwin";
pub(crate) const MACOS_X86_64: &str = "x86_64-apple-darwin";
pub(crate) const LINUX_ARM64: &str = "aarch64-unknown-linux-gnu";
pub(crate) const LINUX_X86_64: &str = "x86_64-unknown-linux-gnu";

/// The sha256 a formula carries before any release exists. Not a plausible hash: 64 zeroes is
/// recognisable at a glance, and Homebrew refuses the download rather than installing something
/// unverified.
pub(crate) const PLACEHOLDER_SHA256: &str =
    "0000000000000000000000000000000000000000000000000000000000000000";

/// One checksum per published archive.
pub(crate) struct Checksums<'a> {
    pub macos_arm64: &'a str,
    pub macos_x86_64: &'a str,
    pub linux_arm64: &'a str,
    pub linux_x86_64: &'a str,
}

impl Checksums<'_> {
    fn all(&self) -> [&str; 4] {
        [
            self.macos_arm64,
            self.macos_x86_64,
            self.linux_arm64,
            self.linux_x86_64,
        ]
    }
}

/// Where a GitHub release keeps its files: the formula's urls are this plus an archive name.
pub(crate) fn default_url_base(version: &str) -> String {
    format!("https://github.com/rfoerthe/cryptomator-cli/releases/download/v{version}")
}

/// The url of one archive, named by [`crate::dist::archive_name`] so the formula cannot disagree
/// with what `xtask dist` uploaded.
pub(crate) fn archive_url(url_base: &str, version: &str, target: &str) -> String {
    format!(
        "{}/{}",
        url_base.trim_end_matches('/'),
        archive_name(version, target)
    )
}

/// The formula text for one release. A template with holes rather than a file to edit: the urls
/// and the checksums change every time, and a stale sha256 fails at install time.
///
/// A placeholder checksum adds a TODO line, so a formula that was rendered before the release
/// exists says so in its first three lines instead of failing silently for whoever tries it.
pub(crate) fn render_formula(version: &str, url_base: &str, sums: &Checksums) -> String {
    let todo = if sums.all().contains(&PLACEHOLDER_SHA256) {
        "# TODO: replace after the first release -- the checksums below are placeholders and no\n\
         # download can match them. `cargo xtask formula --version <v> --sha256-… <hex>` renders\n\
         # the real ones from the SHA256SUMS the release workflow attached.\n"
    } else {
        ""
    };
    let macos_arm64_url = archive_url(url_base, version, MACOS_ARM64);
    let macos_x86_64_url = archive_url(url_base, version, MACOS_X86_64);
    let linux_arm64_url = archive_url(url_base, version, LINUX_ARM64);
    let linux_x86_64_url = archive_url(url_base, version, LINUX_X86_64);
    let Checksums {
        macos_arm64,
        macos_x86_64,
        linux_arm64,
        linux_x86_64,
    } = *sums;
    format!(
        r##"# Homebrew formula for crypto, the Cryptomator command line client.
#
# Generated by `cargo xtask formula`; do not edit by hand. See docs/release.md.
{todo}class Crypto < Formula
  desc "Cryptomator vaults from the command line"
  homepage "https://github.com/rfoerthe/cryptomator-cli"
  version "{version}"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "{macos_arm64_url}"
      sha256 "{macos_arm64}"
    else
      url "{macos_x86_64_url}"
      sha256 "{macos_x86_64}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "{linux_arm64_url}"
      sha256 "{linux_arm64}"
    else
      url "{linux_x86_64_url}"
      sha256 "{linux_x86_64}"
    end
  end

  def install
    bin.install "crypto"
    man1.install Dir["man/*.1"]
    bash_completion.install "completions/crypto.bash" => "crypto"
    zsh_completion.install "completions/_crypto"
    fish_completion.install "completions/crypto.fish"
    doc.install "README.md", "CHANGELOG.md", "LICENSE"
  end

  def caveats
    <<~EOS
      crypto does not ship a file system driver. To mount a vault as a directory,
      install one:

        macOS  brew install --cask macos-fuse-t/homebrew-cask/fuse-t  (no kernel extension)
               brew install --cask macfuse                            (system extension, needs a reboot)
        Linux  fuse3, from your distribution's package manager

      Without a driver, `crypto unlock --mounter webdav` serves the vault over a
      loopback WebDAV server and needs none at all.

      `crypto completions <shell>` prints a completion script if you would rather
      install one by hand than use the ones this formula placed.
    EOS
  end

  test do
    assert_match "crypto {version}", shell_output("#{{bin}}/crypto --version")
    assert_match "#compdef crypto", shell_output("#{{bin}}/crypto completions zsh")
  end
end
"##
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    const MAC_ARM: &str = "1111111111111111111111111111111111111111111111111111111111111111";
    const MAC_X86: &str = "2222222222222222222222222222222222222222222222222222222222222222";
    const LIN_ARM: &str = "3333333333333333333333333333333333333333333333333333333333333333";
    const LIN_X86: &str = "4444444444444444444444444444444444444444444444444444444444444444";

    fn sums() -> Checksums<'static> {
        Checksums {
            macos_arm64: MAC_ARM,
            macos_x86_64: MAC_X86,
            linux_arm64: LIN_ARM,
            linux_x86_64: LIN_X86,
        }
    }

    fn placeholders() -> Checksums<'static> {
        Checksums {
            macos_arm64: PLACEHOLDER_SHA256,
            macos_x86_64: PLACEHOLDER_SHA256,
            linux_arm64: PLACEHOLDER_SHA256,
            linux_x86_64: PLACEHOLDER_SHA256,
        }
    }

    fn rendered() -> String {
        render_formula("0.1.0", &default_url_base("0.1.0"), &sums())
    }

    /// The text between two markers -- one `on_macos`/`on_linux` block, or one branch of it.
    fn between<'a>(text: &'a str, start: &str, end: &str) -> &'a str {
        let from = text.find(start).unwrap_or_else(|| panic!("no `{start}`")) + start.len();
        let rest = &text[from..];
        let to = rest
            .find(end)
            .unwrap_or_else(|| panic!("no `{end}` after `{start}`"));
        &rest[..to]
    }

    fn repo_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("xtask has a parent directory")
            .to_path_buf()
    }

    /// The shape Homebrew needs: a class, the version, the licence, and the two platform blocks.
    #[test]
    fn the_formula_carries_the_version_and_the_licence() {
        let formula = rendered();
        assert!(formula.contains("class Crypto < Formula"));
        assert!(formula.contains(r#"version "0.1.0""#));
        assert!(formula.contains(r#"license "AGPL-3.0-only""#));
        assert!(formula.contains("on_macos do"));
        assert!(formula.contains("on_linux do"));
        // No `depends_on :macos`: Homebrew on Linux installs the Linux archive.
        assert!(!formula.contains("depends_on :macos"));
    }

    /// Each of the four branches has to pair *its own* archive with *its own* checksum: a
    /// copy-and-paste that gives the Intel branch the arm64 hash fails the download for everyone
    /// on an Intel Mac and for nobody else.
    #[test]
    fn each_platform_branch_pairs_its_own_url_and_checksum() {
        let formula = rendered();
        let macos = between(&formula, "on_macos do", "\n  end");
        let linux = between(&formula, "on_linux do", "\n  end");
        for (block, arm_target, arm_sha, intel_target, intel_sha) in [
            (macos, MACOS_ARM64, MAC_ARM, MACOS_X86_64, MAC_X86),
            (linux, LINUX_ARM64, LIN_ARM, LINUX_X86_64, LIN_X86),
        ] {
            assert!(block.contains("if Hardware::CPU.arm?"), "no arm branch");
            let arm = between(block, "if Hardware::CPU.arm?", "else");
            let intel = between(block, "else", "end");
            for (branch, target, sha) in
                [(arm, arm_target, arm_sha), (intel, intel_target, intel_sha)]
            {
                let url = archive_url(&default_url_base("0.1.0"), "0.1.0", target);
                assert!(
                    branch.contains(&format!(r#"url "{url}""#)),
                    "the branch for {target} does not point at {url}: {branch}"
                );
                assert!(
                    branch.contains(&format!(r#"sha256 "{sha}""#)),
                    "the branch for {target} carries the wrong checksum: {branch}"
                );
            }
        }
        // Four archives, four checksums, and no others.
        assert_eq!(formula.matches("url \"").count(), 4);
        assert_eq!(formula.matches("sha256 \"").count(), 4);
    }

    /// The caveats are the whole reason a FUSE-less binary is installable at all: without a
    /// driver, `crypto unlock` falls back to WebDAV and the user has to be told.
    #[test]
    fn the_caveats_name_both_fuse_options_and_the_webdav_fallback() {
        let formula = rendered();
        let caveats = between(&formula, "def caveats", "EOS\n  end");
        for fragment in ["fuse-t", "macfuse", "fuse3", "--mounter webdav"] {
            assert!(
                caveats.contains(fragment),
                "caveats do not mention {fragment}"
            );
        }
    }

    /// Everything the archive carries has to be installed, or the package is worse than the
    /// tarball it came from.
    #[test]
    fn it_installs_the_binary_the_pages_and_the_completions() {
        let formula = rendered();
        for fragment in [
            r#"bin.install "crypto""#,
            "man1.install",
            "bash_completion.install",
            "zsh_completion.install",
            "fish_completion.install",
        ] {
            assert!(
                formula.contains(fragment),
                "the formula does not install {fragment}"
            );
        }
        // Homebrew's own check that the binary starts at all.
        assert!(formula.contains(r##"shell_output("#{bin}/crypto --version")"##));
    }

    /// A rendering nobody can install yet says so; a real one carries no TODO for a reader to
    /// wonder about.
    #[test]
    fn a_placeholder_checksum_is_flagged_and_a_real_one_is_not() {
        let placeholder = render_formula("0.1.0", &default_url_base("0.1.0"), &placeholders());
        assert!(placeholder.contains("# TODO: replace after the first release"));
        assert_eq!(placeholder.matches(PLACEHOLDER_SHA256).count(), 4);
        assert!(!rendered().contains("TODO"));
    }

    /// `ruby -c` is the only judge of whether Homebrew can even load the file. Skipped where no
    /// ruby is installed rather than silently passing on a broken template.
    #[test]
    fn the_rendered_formula_is_valid_ruby() {
        let dir = tempfile::tempdir().expect("a temporary directory");
        let path = dir.path().join("crypto.rb");
        std::fs::write(&path, rendered()).expect("the formula is writable");
        let out = match std::process::Command::new("ruby")
            .arg("-c")
            .arg(&path)
            .output()
        {
            Ok(out) => out,
            Err(_) => {
                eprintln!("skipped: no ruby on this machine");
                return;
            }
        };
        assert!(
            out.status.success(),
            "ruby -c rejected the formula: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }

    /// The four `sha256` values of a formula, in the order the template writes them: macOS arm64,
    /// macOS x86_64, Linux arm64, Linux x86_64.
    fn checksums_of(formula: &str) -> Vec<String> {
        formula
            .lines()
            .filter_map(|line| line.trim().strip_prefix(r#"sha256 ""#))
            .filter_map(|rest| rest.strip_suffix('"'))
            .map(str::to_owned)
            .collect()
    }

    /// The committed formula is a rendering and nothing else: an edit by hand would be overwritten
    /// by the next `--write` without anyone noticing which of the two was right.
    ///
    /// The four checksums are read back out of the file instead of being fixed here, because the
    /// committed formula has two legitimate states: placeholders before a release exists, and the
    /// release's real hashes after the back-port of `docs/release.md` step 3. Everything else --
    /// the version, the four urls, the install block, the caveats -- still has to be exactly what
    /// the renderer produces for the version in `Cargo.toml`.
    #[test]
    fn the_committed_formula_is_what_the_renderer_produces() {
        let path = repo_root().join("packaging/homebrew/crypto.rb");
        let committed =
            std::fs::read_to_string(&path).expect("packaging/homebrew/crypto.rb exists");
        let sums = checksums_of(&committed);
        assert_eq!(sums.len(), 4, "the formula does not carry four checksums");
        for sum in &sums {
            assert!(
                sum.len() == 64
                    && sum
                        .bytes()
                        .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b)),
                "{sum} is not a lowercase 64-digit sha256"
            );
        }
        let version = crate::dist::VERSION;
        assert_eq!(
            committed,
            render_formula(
                version,
                &default_url_base(version),
                &Checksums {
                    macos_arm64: &sums[0],
                    macos_x86_64: &sums[1],
                    linux_arm64: &sums[2],
                    linux_x86_64: &sums[3],
                },
            ),
            "packaging/homebrew/crypto.rb is stale; re-render it -- with the release's four \
             checksums if it already carries them, because a bare `cargo xtask formula --write` \
             puts the placeholders back"
        );
    }
}
