# Homebrew formula for crypto, the Cryptomator command line client.
#
# Generated by `cargo xtask formula`; do not edit by hand. See docs/release.md.
# TODO: replace after the first release -- the checksums below are placeholders and no
# download can match them. `cargo xtask formula --version <v> --sha256-… <hex>` renders
# the real ones from the SHA256SUMS the release workflow attached.
class Crypto < Formula
  desc "Cryptomator vaults from the command line"
  homepage "https://github.com/rfoerthe/cryptomator-cli"
  version "0.1.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rfoerthe/cryptomator-cli/releases/download/v0.1.0/crypto-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://github.com/rfoerthe/cryptomator-cli/releases/download/v0.1.0/crypto-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/rfoerthe/cryptomator-cli/releases/download/v0.1.0/crypto-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://github.com/rfoerthe/cryptomator-cli/releases/download/v0.1.0/crypto-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "crypto"
    man1.install Dir["man/*.1"]
    bash_completion.install "completions/crypto.bash" => "crypto"
    zsh_completion.install "completions/_crypto"
    fish_completion.install "completions/crypto.fish"
    doc.install "README.md", "CHANGELOG.md", "LICENSE"
  end

  def caveats
    <<~EOS
      crypto does not ship a file system driver. To mount a vault as a directory,
      install one:

        macOS  brew install --cask macos-fuse-t/homebrew-cask/fuse-t  (no kernel extension)
               brew install --cask macfuse                            (system extension, needs a reboot)
        Linux  fuse3, from your distribution's package manager

      Without a driver, `crypto unlock --mounter webdav` serves the vault over a
      loopback WebDAV server and needs none at all.

      `crypto completions <shell>` prints a completion script if you would rather
      install one by hand than use the ones this formula placed.
    EOS
  end

  test do
    assert_match "crypto 0.1.0", shell_output("#{bin}/crypto --version")
    assert_match "#compdef crypto", shell_output("#{bin}/crypto completions zsh")
  end
end
