# Homebrew formula for crypto, the Cryptomator command line client.
#
# Generated by `cargo xtask formula`; do not edit by hand. See docs/release.md.
class Crypto < Formula
  desc "Cryptomator vaults from the command line"
  homepage "https://github.com/rfoerthe/cryptomator-cli"
  version "0.1.1"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rfoerthe/cryptomator-cli/releases/download/v0.1.1/crypto-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "178f4f5a8914153f2f2a5d947056c6cbad2b52906ba913d99214e389bb91eb84"
    else
      url "https://github.com/rfoerthe/cryptomator-cli/releases/download/v0.1.1/crypto-0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "f449e77beda2a7f633bbaf7b9844fbd93008f7d51320edeac353397b37f6b0ed"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/rfoerthe/cryptomator-cli/releases/download/v0.1.1/crypto-0.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "940cad42c85a4b5a9057793f937d331a622ebcc739edf9564d4ee2dcee8ab1fc"
    else
      url "https://github.com/rfoerthe/cryptomator-cli/releases/download/v0.1.1/crypto-0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "54fd3f131c8a39948823fd0cddaafa546152ffe6e440533515ba44ec389e4343"
    end
  end

  def install
    bin.install "crypto"
    man1.install Dir["man/*.1"]
    bash_completion.install "completions/crypto.bash" => "crypto"
    zsh_completion.install "completions/_crypto"
    fish_completion.install "completions/crypto.fish"
    doc.install "README.md", "CHANGELOG.md", "LICENSE"
  end

  def caveats
    <<~EOS
      crypto does not ship a file system driver. To mount a vault as a directory,
      install one:

        macOS  brew install --cask macos-fuse-t/homebrew-cask/fuse-t  (no kernel extension)
               brew install --cask macfuse                            (system extension, needs a reboot)
        Linux  fuse3, from your distribution's package manager

      Without a driver, `crypto unlock --mounter webdav` serves the vault over a
      loopback WebDAV server and needs none at all.

      `crypto completions <shell>` prints a completion script if you would rather
      install one by hand than use the ones this formula placed.
    EOS
  end

  test do
    assert_match "crypto 0.1.1", shell_output("#{bin}/crypto --version")
    assert_match "#compdef crypto", shell_output("#{bin}/crypto completions zsh")
  end
end
